owner: Samasaur1
repo: upptime

sites:
  - name: samasaur.com
    url: https://samasaur.com
  - name: Vaultwarden instance
    url: https://vault.samasaur.com
  - name: Media server
    url: https://watch.samasaur.com
  - name: Blog
    url: https://samasaur1.github.io
  - name: Status page (this site)
    url: https://status.samasaur.com
  - name: Factor puzzle of the day
    url: https://factor.samasaur.com/puzzle.json

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.samasaur.com
  # TODO: fill out the rest of these later
  logoUrl: https://icons.duckduckgo.com/ip3/samasaur1.github.io.ico
  name: Samasaur1 | Status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: light

assignees:
  - Samasaur1
